export const BOOKS_DATA = [
  {
    media: '/assets/images/vertigo-obalka-1.png',
    title: 'Vertigo 4/2025',
    author: '',
    genreID: 2,
    label: 'Tak pekne rozprávaš po slovensky ani prízvuk nemáš',
    date: '2025-12-20',
    img: '',
    pdf: 'https://cs.wikipedia.org/wiki/Portable_Document_Format',
    href: 'https://www.artforum.sk/katalog/181748/vertigo-22023-priloha-poldoba-rozpadu',
  },
  {
    media: '/assets/images/kniha-obalka-1.jpg',
    title: ' Spoločný jazyk',
    author: 'Jürg Halter',
    genreID: 2,
    label:
      'Zahľadíš sa na strop, nadchnutý vlastným nešťastím, pomaly prerastáš sám seba.',
    date: '2025-12-10',
    img: '',
    pdf: '',
    href: 'https://www.artforum.sk/katalog/186108/slovnik-diel-slovenskej-literatury-po-roku-1989',
  },
  {
    media: '/assets/images/vertigo-obalka-2.png',
    title: 'Vertigo 3/2025',
    author: '',
    genreID: 1,
    label: '',
    date: '2025-11-20',
    img: '',
    pdf: '',
    href: 'https://www.artforum.sk/katalog/170542/vertigo-12022-kniha-rozkvitni-pre-seba',
  },
  {
    media: '/assets/images/vertigo-obalka-3.png',
    title: 'Vertigo 2/2025',
    author: '',
    genreID: 1,
    label: 'Do konca prázdnin ostávali ešte tri týždne.',
    date: '2025-10-20',
    img: '',
    pdf: 'https://cs.wikipedia.org/wiki/Portable_Document_Format',
    href: 'https://www.artforum.sk/katalog/160739/vertigo-1-22021-kniha-nespavost',
  },
  {
    media: '/assets/images/vertigo-obalka-4.png',
    title: 'Vertigo 1/2025',
    author: '',
    genreID: 1,
    label: '',
    date: '2025-09-20',
    img: '',
    pdf: 'https://cs.wikipedia.org/wiki/Portable_Document_Format',
    href: '',
  },
  {
    media: '/assets/images/vertigo-obalka-1.png',
    title: 'Vertigo 4/2025',
    author: '',
    genreID: 1,
    label: 'Tak pekne rozprávaš po slovensky ani prízvuk nemáš',
    date: '2025-12-20',
    img: '',
    href: 'https://www.artforum.sk/katalog/181748/vertigo-22023-priloha-poldoba-rozpadu',
  },
  {
    media: '/assets/images/kniha-obalka-1.jpg',
    title: ' Spoločný jazyk',
    author: 'Jürg Halter',
    genreID: 3,
    label:
      'Zahľadíš sa na strop, nadchnutý vlastným nešťastím, pomaly prerastáš sám seba.',
    date: '2025-12-10',
    img: '',
    pdf: '',
    href: 'https://www.artforum.sk/katalog/186108/slovnik-diel-slovenskej-literatury-po-roku-1989',
  },
  {
    media: '/assets/images/vertigo-obalka-2.png',
    title: 'Vertigo 3/2025',
    author: '',
    genreID: 3,
    label: '',
    date: '2025-11-20',
    img: '',
    pdf: '',
    href: 'https://www.artforum.sk/katalog/170542/vertigo-12022-kniha-rozkvitni-pre-seba',
  },
  {
    media: '/assets/images/vertigo-obalka-3.png',
    title: 'Vertigo 2/2025',
    author: '',
    genreID: 3,
    label: 'Do konca prázdnin ostávali ešte tri týždne.',
    date: '2025-10-20',
    img: '',
    pdf: 'https://cs.wikipedia.org/wiki/Portable_Document_Format',
    href: 'https://www.artforum.sk/katalog/160739/vertigo-1-22021-kniha-nespavost',
  },
  {
    media: '/assets/images/vertigo-obalka-4.png',
    title: 'Vertigo 1/2025',
    author: '',
    genreID: 3,
    label: '',
    date: '2025-09-20',
    img: '',
    pdf: 'https://cs.wikipedia.org/wiki/Portable_Document_Format',
    href: '',
  },
  {
    media: '/assets/images/vertigo-obalka-1.png',
    title: 'Vertigo 4/2025',
    author: '',
    genreID: 4,
    label: 'Tak pekne rozprávaš po slovensky ani prízvuk nemáš',
    date: '2025-12-20',
    img: '',
    pdf: 'https://cs.wikipedia.org/wiki/Portable_Document_Format',
    href: 'https://www.artforum.sk/katalog/181748/vertigo-22023-priloha-poldoba-rozpadu',
  },
  {
    media: '/assets/images/kniha-obalka-1.jpg',
    title: ' Spoločný jazyk',
    author: 'Jürg Halter',
    genreID: 4,
    label:
      'Zahľadíš sa na strop, nadchnutý vlastným nešťastím, pomaly prerastáš sám seba.',
    date: '2025-12-10',
    img: '',
    pdf: '',
    href: 'https://www.artforum.sk/katalog/186108/slovnik-diel-slovenskej-literatury-po-roku-1989',
  },
  {
    media: '/assets/images/vertigo-obalka-2.png',
    title: 'Vertigo 3/2025',
    author: '',
    genreID: 4,
    label: '',
    date: '2025-11-20',
    img: '',
    pdf: '',
    href: 'https://www.artforum.sk/katalog/170542/vertigo-12022-kniha-rozkvitni-pre-seba',
  },
  {
    media: '/assets/images/vertigo-obalka-3.png',
    title: 'Vertigo 2/2025',
    author: '',
    genreID: 4,
    label: 'Do konca prázdnin ostávali ešte tri týždne.',
    date: '2025-10-20',
    img: '',
    pdf: 'https://cs.wikipedia.org/wiki/Portable_Document_Format',
    href: 'https://www.artforum.sk/katalog/160739/vertigo-1-22021-kniha-nespavost',
  },
  {
    media: '/assets/images/vertigo-obalka-1.png',
    title: 'Vertigo 4/2025',
    author: '',
    genreID: 5,
    label: 'Tak pekne rozprávaš po slovensky ani prízvuk nemáš',
    date: '2025-12-20',
    img: '',
    pdf: 'https://cs.wikipedia.org/wiki/Portable_Document_Format',
    href: 'https://www.artforum.sk/katalog/181748/vertigo-22023-priloha-poldoba-rozpadu',
  },
  {
    media: '/assets/images/kniha-obalka-1.jpg',
    title: ' Spoločný jazyk',
    author: 'Jürg Halter',
    genreID: 5,
    label:
      'Zahľadíš sa na strop, nadchnutý vlastným nešťastím, pomaly prerastáš sám seba.',
    date: '2025-12-10',
    img: '',
    pdf: '',
    href: 'https://www.artforum.sk/katalog/186108/slovnik-diel-slovenskej-literatury-po-roku-1989',
  },
  {
    media: '/assets/images/vertigo-obalka-2.png',
    title: 'Vertigo 3/2025',
    author: '',
    genreID: 5,
    label: '',
    date: '2025-11-20',
    img: '',
    pdf: '',
    href: 'https://www.artforum.sk/katalog/170542/vertigo-12022-kniha-rozkvitni-pre-seba',
  },
  {
    media: '/assets/images/vertigo-obalka-3.png',
    title: 'Vertigo 2/2025',
    author: '',
    genreID: 5,
    label: 'Do konca prázdnin ostávali ešte tri týždne.',
    date: '2025-10-20',
    img: '',
    pdf: 'https://cs.wikipedia.org/wiki/Portable_Document_Format',
    href: 'https://www.artforum.sk/katalog/160739/vertigo-1-22021-kniha-nespavost',
  },
];
